MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'vgg'
        PRETRAINED: True
        #OUT_CHANNELS: [128, 256, 128, 128, 64, 64]
        OUT_CHANNELS: [512, 1024, 512, 256, 256, 256]
        INPUT_CHANNELS: 3
#TRANSFORMATIONS:
#    RANDOMMIRROR: False
INPUT:
    IMAGE_SIZE: 300
DATASETS:
    TRAIN: ("tdt4265_train",)
    TEST: ("tdt4265_val", )
SOLVER:
    MAX_ITER: 120000
    LR_STEPS: [80000, 100000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    #LR: 1e-3
    LR: 1e-4
OUTPUT_DIR: 'outputs/VGG'
DATASET_DIR: "datasets"