MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'vgg'
        PRETRAINED: False
        #OUT_CHANNELS: [128, 256, 128, 128, 64, 64]
        OUT_CHANNELS: [512, 1024, 512, 256, 256, 256]
        INPUT_CHANNELS: 3
INPUT:
    IMAGE_SIZE: 300
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
SOLVER:
    MAX_ITER: 36000
    LR_STEPS: [28000, 32000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 5e-3
    WARMUP_ITERS: 1500
    WARMUP_FACTOR: 0.05
OUTPUT_DIR: 'outputs/v2_4_decreased_lr'
DATASET_DIR: "datasets"
